"""campaigns"""
from alembic import op
import sqlalchemy as sa


revision = '005'
down_revision = '004a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('segment_revision_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('objective', sa.String(length=500), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('benefit', sa.String(length=1000), nullable=False),
    sa.Column('brand_tone', sa.String(length=200), nullable=False),
    sa.Column('primary_kpi', sa.String(length=40), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('planned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('coupon_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='DRAFT', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('policy_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("channel IN ('EMAIL','PUSH','SMS')", name=op.f('ck_campaigns_channel')),
    sa.CheckConstraint("status IN ('DRAFT','REVIEW','APPROVED','RUNNING','COMPLETED','CANCELLED')", name=op.f('ck_campaigns_status')),
    sa.CheckConstraint('version > 0 AND policy_version > 0 AND target_value >= 0', name=op.f('ck_campaigns_values')),
    sa.ForeignKeyConstraint(['dataset_id', 'segment_revision_id'], ['segment_revisions.dataset_id', 'segment_revisions.id'], name=op.f('fk_campaigns_dataset_id_segment_revisions')),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_campaigns_dataset_id_datasets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns')),
    sa.UniqueConstraint('dataset_id', 'id', name='uq_campaign_dataset')
    )
    op.create_table('campaign_exclusions',
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('segment_revision_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id', 'campaign_id'], ['campaigns.dataset_id', 'campaigns.id'], name=op.f('fk_campaign_exclusions_dataset_id_campaigns')),
    sa.ForeignKeyConstraint(['dataset_id', 'segment_revision_id'], ['segment_revisions.dataset_id', 'segment_revisions.id'], name=op.f('fk_campaign_exclusions_dataset_id_segment_revisions')),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_campaign_exclusions_dataset_id_datasets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_exclusions')),
    sa.UniqueConstraint('campaign_id', 'segment_revision_id', name='uq_campaign_exclusion')
    )
    op.create_table('campaign_variants',
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('variant_name', sa.String(length=1), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('hypothesis', sa.String(length=1000), nullable=False),
    sa.Column('allocation_bp', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("variant_name IN ('A','B')", name=op.f('ck_campaign_variants_name')),
    sa.CheckConstraint('allocation_bp > 0 AND allocation_bp < 10000', name=op.f('ck_campaign_variants_allocation')),
    sa.ForeignKeyConstraint(['dataset_id', 'campaign_id'], ['campaigns.dataset_id', 'campaigns.id'], name=op.f('fk_campaign_variants_dataset_id_campaigns')),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_campaign_variants_dataset_id_datasets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_variants')),
    sa.UniqueConstraint('campaign_id', 'variant_name', name='uq_campaign_variant_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaign_variants')
    op.drop_table('campaign_exclusions')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
