"""ai_campaign_proposals"""
from alembic import op
import sqlalchemy as sa


revision = '005a'
down_revision = '005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_action_proposals', sa.Column('action_type', sa.String(length=30), server_default='SEGMENT', nullable=False))
    op.add_column('ai_action_proposals', sa.Column('campaign_id', sa.Uuid(), nullable=True))
    op.add_column('ai_action_proposals', sa.Column('data_version', sa.Integer(), nullable=True))
    op.add_column('ai_action_proposals', sa.Column('policy_version', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_ai_action_proposals_dataset_id_campaigns'), 'ai_action_proposals', 'campaigns', ['dataset_id', 'campaign_id'], ['dataset_id', 'id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_ai_action_proposals_dataset_id_campaigns'), 'ai_action_proposals', type_='foreignkey')
    op.drop_column('ai_action_proposals', 'policy_version')
    op.drop_column('ai_action_proposals', 'data_version')
    op.drop_column('ai_action_proposals', 'campaign_id')
    op.drop_column('ai_action_proposals', 'action_type')
    # ### end Alembic commands ###
